apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: NewsWarehouse
    type: postgres
    access: proxy
    url: warehouse:5432
    database: warehouse
    user: warehouse
    secureJsonData:
      password: warehouse
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    editable: false
